language: go

go_import_path: github.com/romainmenke/pusher

go:
- 1.6.x
- 1.7.x
- 1.8.x
- master

script:
  on:
    condition: $TRAVIS_GO_VERSION =~ ^1\.6\.[0-9]+$
  - go test -v ./common/...
  - go test -v ./link/...
  - go test -v ./parser/...
  - go test -v ./rules/...

script:
  on:
    condition: $TRAVIS_GO_VERSION =~ ^1\.7\.[0-9]+$
  - go test -v ./common/...
  - go test -v ./link/...
  - go test -v ./parser/...
  - go test -v ./rules/...

script:
  on:
    condition: $TRAVIS_GO_VERSION =~ ^1\.8\.[0-9]+$
  - go test -v ./...
  - bash ./go.test.sh

after_success:
  on:
    condition: $TRAVIS_GO_VERSION =~ ^1\.8\.[0-9]+$
  - bash <(curl -s https://codecov.io/bash)
