language: go

go_import_path: github.com/romainmenke/pusher

go:
- 1.6.x
- 1.7.x
- 1.8.x
- master

script:
  - go test -v ./...

script:
  - bash ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
